/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-02-17 19:26:41 
*/
import java.rmi.Remote;
import java.rmi.RemoteException;

public interface RMIInterface extends Remote {
    String sayHello(String name) throws RemoteException;
    
    abstract CommnicationInfo check(CommnicationInfo info) throws RemoteException;
    abstract void push(CommnicationInfo info) throws RemoteException;
    
}
