/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-02-17 19:26:41 
*/
import java.rmi.Remote;
import java.rmi.RemoteException;
/**
 * The interface of the RMIInterface
 */
public interface RMIInterface extends Remote {
    /**
     * Check the file in the server.
     * @param info CommunicationInfo.
     * @return ComminicationInfo
     * @throws RemoteException thorw RemoteException when error occurs.
     */
    abstract CommnicationInfo check(CommnicationInfo info) throws RemoteException;

    /**
     * Push the information from Proxy to the server.
     * @param info CommunicationInfo
     * @throws RemoteException thorw RemoteException when error occurs.
     */
    abstract void push(CommnicationInfo info) throws RemoteException;
    
}
